### ISSUE TITLE
Custom computations

### ISSUE THREAD

**Issue by mortendahl** [capeprivacy/pycape#122]
This would let a user of pycape specify a custom computation to run. The computation could do anything, not just linear regression!

Note: This feature is still being designed, so some of the sample APIs and implementation strategies are subject to change.

## Sample API

I think we could build this feature as part of the [Jobs api](https://docs.capeprivacy.com/libraries/pycape/usage/job/).

```python
my_project = c.get_project(id="project_123")

user_a = edsl.host_placement(name="user-a")
user_b = edsl.host_placement(name="user-b")

def my_computation(
  arg_a: edsl.Argument(placement=user_a)
  arg_b: edsl.Argument(placement=user_b)
):

  with user_a:
    # do stuff

  with user_b:
    # do stuff

  return res

cc = CustomComputation(
  computation=my_computation,
  user_a = organizations[0],
  user_b = organizations[1],
  arg_a = # not sure??
  arg_b = # not sure??  
)

my_project.submit_job(job=cc)
```

We could use kwargs to specify the properties the computation needs (which org will be which host placement), or simple dictionaries if we wanted to be more explicit

```python
cc = CustomComputation(
  computation=my_computation,
  placements={
    'user_a': organizations[0],
    'user_b': organizations[1]
  },
  arguments={
    'arg_a': ???
    'arg_b': ???
  }
)
```

## Open Questions

- How do you specify things the cape worker should do? Perhaps we can offer an API for this?
```python
user_a = edsl.host_placement(name="user-a")
user_b = edsl.host_placement(name="user-b")
cape_worker = cape.get_cape_host_placement() ???
```

- If you wanted to specify constants for arguments, the dataviews API might be heavy, what could that look like? E.g., we might want to accept a simple numpy array

**Comment by mortendahl** [comment]
Current PRs:
- https://github.com/tf-encrypted/runtime/pull/303
- https://github.com/tf-encrypted/runtime/pull/306

**Comment by kjam** [comment]
In case this is also useful, here are the high-level designs for how this might be used by the user in pycape from @yanndupis 

https://github.com/capeprivacy/cppib-pilot/tree/data-transform/data-transform-api-mocked-up

**Comment by gifteconomist** [comment]
Closing this issue since it was moved to 'Done' in the Active Backlog.
