### ISSUE TITLE
Write a pycape release checklist

### ISSUE THREAD

**Issue by justin1121** [capeprivacy/pycape#136]
We should write a pycape release checklist so that anyone can handle releasing pycape.

@gifteconomist would you mind adding what you do right now? And then we can collab on it. Thanks!

**Comment by gifteconomist** [comment]
Thanks for opening this. Current workflow:
- Manually bump the version [here](https://github.com/capeprivacy/pycape/blob/main/pyproject.toml#L3) in the `pyproject.toml` depending on what kind of release it is.
- `poetry publish --build`
